### ISSUE TITLE
Not all VM Config Data is populating

### ISSUE THREAD

**Issue by wsdismukes** [Zerto-TA-Public/zplanner#31]
Line 46 of zplanner/workers/vm-vminfo.ps1 is missing the "9" in the file name and prevents full VM config data population. I believe Line 46 should read:

if (Test-Path "/home/zerto/data/vmlist9.csv") {

**Comment by recklessop** [comment]
Awesome catch! I added your fix to the file on this commit https://github.com/Zerto-TA-Public/zplanner/commit/d618ce50675523a568451e310485b27fbe78b52d 

You should be able to update the zplanner from the console menu and get the latest code with the fix.

Thanks again!

**Comment by recklessop** [comment]
Updated File in question with the proper filename and committed to master repo. zPlanner users can update their appliance from the console manually, or the update will push automatically after midnight.

**Comment by wsdismukes** [comment]
Thanks for the quick turnaround!
